# Resources


1. https://github.com/slundberg/shap SHAP
2. https://github.com/marcotcr/lime LIME
3. Book on interpretability and explainable ML https://christophm.github.io/interpretable-ml-book/

In [1]:
import pandas as pd

In [8]:
# df_reg = pd.read_csv('https://raw.githubusercontent.com/kurmukovai/ds-for-business/main/seminar-2/laptop_price.csv',  encoding='latin-1')
df_clf = pd.read_csv('https://raw.githubusercontent.com/kurmukovai/ds-for-business/main/seminar-1/AER_credit_card_data.csv')


- card: `target` 1 if credit card application accepted, 0 if not 
- reports: Number of major derogatory reports
- age: Age n years plus twelfths of a year
- income: Yearly income (divided by 10,000)
- share: Ratio of monthly credit card expenditure to yearly income
- expenditure: Average monthly credit card expenditure
- owner: 1 if owns home, 0 if rents
- selfempl: 1 if self-employed, 0 if not
- dependents: 1 + number of dependents
- months: Months living at current address
- majorcards: Number of major credit cards held
- active: Number of active credit accounts

share, expenditure, active, majorcards

In [16]:
df_clf.head(5)

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12
1,yes,0,33.25000,2.4200,0.005217,9.854167,no,no,3,34,1,13
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,58,1,5
3,yes,0,30.50000,2.5400,0.065214,137.869200,no,no,0,25,1,7
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5

# Plan

1. Linear model
2. Decision tree
3. Feature Shuffle
4. SHAP
5. LIME
6. catboost

- Агностичны к модели (Feature Shuffle, SHAP, LIME)
- Model based, model internals (LM, DT, Catboost)

----

- Описывают модель целиком
- Дают интерпретацию конкретному предсказанию (наблюдению) -> LIME (local interpretable model explainer), Decison Tree

In [ ]:
- Все это считается для фиксированного набора признаков.

------------
Linear Model -> веса чем больше вес по модулю тем "важнее" признак
-> one importance "to rule them all" 
-> model based, если  используете GBT, то feature importance linear model вам бесполезен
------------
Decision tree -> 
- Посчитать количество сплитов по признаку 63-1,2,3,4,5
- Information gain (clf) / MSE
-> сложно интерпретировать
-> нестабильность
------------
Feature Shuffle - model agnostic

clf, X

clf(X) -> A
shuffle(x^1) -> clf(X^1) -> A1
shuffle(x^2) -> clf(X^2) -> A2
...
delta = A-A1 
-----------
LIME
-> computationally expensive
------------
L <- V, T, .....
Shapley Values
Вектор Шепли